import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Layout.module.scss";

// import { Header, Footer, Sidebar } from "@/components";
import Login from "./Login";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Layout() {
  return (
    <>
      <Head>
        <title>Manage Project Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Login/>
        {/* <Header />
        <main className={styles.main}>
          <Sidebar />
          <Login />
          <section className={styles.content}>
   
            This is content
          </section>
        </main>
        <Footer /> */}
      </div>
    </>
  );
}
